[main]
# The default PPD profile
default=balanced
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
# PPD = TuneD
performance=throughput-performance
balanced=balanced-ac-custom
power-saver=powersave-custom

[battery]
# PPD = TuneD
balanced=balanced-battery-custom
