name: solarpowered-ex
on:
  schedule:
    - cron: "00 17 * * 1,4" # build at 17:00 UTC Mondays and Thursdays
    
  push:
    paths: # trigger build only if solarpowered-ex.yml is updated
      - "recipes/solarpowered-ex.yml"
      
  pull_request: # allow PRs triggering builds
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Build solarpowered-ex
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - solarpowered-ex.yml
    steps:
       # the build is fully handled by the reusable github action
      - name: Build Custom Image
        uses: blue-build/github-action@v1.8
        with:
          recipe: ${{ matrix.recipe }}
          rechunk: true
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}